services:
  - type: web
    name: react-interviewbro
    env: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production

